### ISSUE TITLE
Use time of note to judge instead of percentage on screen

### ISSUE THREAD

**Issue by jer123se12** [henryzt/Rhythm-Plus-Music-Game#104]
Currently the timing window changes as the rate changes, at high rates, the judgement window becomes too tight to hit. You could timing based judgment instead, like stepmania.

**Comment by henryz00** [comment]
Good point, I have noticed this before too. This will be fixed soon.

**Comment by henryzt** [comment]
This is now implemented in version 1.2.2 🎉
