### ISSUE TITLE
How do I use the sheet editor

### ISSUE THREAD

**Issue by MilkyYOUNIVERSE** [henryzt/Rhythm-Plus-Music-Game#167]
How do I make the notes appear? I have the sheets filled out, but I don't know how to edit the notes.

**Comment by SleeplessRPlus** [comment]
Hi there! If you look on the right side of your screen in the sheet editor, you can see a list of notes placed! If you click the boxes that are listed under the "Keys" column, it will bring up a menu of things you can change.
(Hope this helps! :D)

![rhythm](https://user-images.githubusercontent.com/98996464/154321509-8233c241-3636-4783-9285-959e181339b9.PNG)

**Comment by dabee206** [comment]
> i don't know how to use the sheet editor at all could someone show me how it works.

(btw i don't have the keys column and hardly any of the buttons work)

**Comment by SleeplessRPlus** [comment]
> dabee206

Before editing the notes, have you managed to place them down first?
This can be done by playing the song and using your note keybinds to place them down. (Just make sure that you're in the chart editing mode and not the chart testing mode too!)
![=w=](https://user-images.githubusercontent.com/98996464/160467359-7b50d975-d69a-46b2-94a2-00863ddbfb2b.PNG)

**Comment by dabee206** [comment]
Ive been trying to play the video but i cant even press the button to start the vid so i don't really know how to edit or even chart notes

**Comment by dabee206** [comment]
heres some screenshots for what problems i have
![Screenshot 2022-03-28 12 28 39 PM](https://user-images.githubusercontent.com/102542965/160473187-4ab0179b-6a6c-4916-983d-7481b60073bb.png)
![Screenshot 2022-03-28 12 28 31 PM](https://user-images.githubusercontent.com/102542965/160473204-c83c7585-b44a-4576-a1d5-5a3f441f135d.png)

**Comment by SleeplessRPlus** [comment]
> Ive been trying to play the video but i cant even press the button to start the vid so i don't really know how to edit or even chart notes
Sorry about the late reply, but now that I see the screenshots I can see what's wrong! You put a link to a YouTube video while the box where you put it was a query for an MP3 file URL.
![Yesn't](https://user-images.githubusercontent.com/98996464/160509350-0b1f1e44-8385-46af-99e0-304a9d96cd90.PNG)
Just make sure that the query matches with what you put in there and it will work!
Another thing that you would like to do, is that if you decide to continue using that link to the video is to use the ID and not the full link. I know it's confusing, but I'm sure it will change in the future!
Example: youtube.com/watch?v=z5EEf931E3Q --> z5EEf931E3Q

Hope this helps!

**Comment by dabee206** [comment]
Oh ok thank you so much for the help i am very appreciative of that thanks for the very big help

**Comment by henryzt** [comment]
@SleeplessRPlus Thank you very much for the help! I'll close the issue for now, if there are any other question please reopen it.
