### ISSUE TITLE
Suggestions and possible bug?

### ISSUE THREAD

**Issue by Kweeme** [henryzt/Rhythm-Plus-Music-Game#185]
### **Possible Bug**

I'll start off with the possible bug...
Every time I try to switch to visualizer OFF it redirects that setting to space visualizer.
Dunno if this is known or if visualizer off is not a feature yet..

### **Suggestions**
I am running on a Chromebook, so you can expect my performance on anything to be absolute shit.
I get jitters randomly while playing a song and average around 20-25 FPS
Same goes with Rythm+

Here are some things that could help me and other potato users.

1. An option to turn off/on video backgrounds.
2. Maybe a potato option.. This option would disable animations, disable some extra CSS shit [Button glow, icon animation, ripple on the play button, etc.] 
or 2. Turn everything that I mentioned in the previous _2._ into a SINGLE option in the settings menu.

These are just suggestions.. please feel free to **COMPLETELY** destroy this thread after fixing that possible bug.

### **Note**
(Before you go "Get a better PC/Laptop", I would LOVE to but I am not in a financial situation for buying things such as a new laptop/PC.)

**Comment by henryzt** [comment]
Thanks for the report! This can be reproduced and confirmed as a bug, fix is on the way.

We are working on improving the performance of the game, and have already planned a full rewrite of the game part to improve performance especially on lower end devices, the video background can't be turn off since we rely on the youtube iframe to play the game, but I'll trying add the low quality mode as you suggested 👍

**Comment by Kweeme** [comment]
> This can be reproduced and confirmed as a bug, fix is on the way.

Great to hear that a fix is on the way.

> the video background can't be turn off since we rely on the youtube iframe to play the game

Does it have to be the youtube video itself or can you do something like an audio only mode?

> I'll trying add the low quality mode as you suggested || have already planned a full rewrite of the game part to improve performance especially on lower end devices

Great to hear that these things are happening! I can't wait to be able to play this game without any issues. <3

**Comment by henryzt** [comment]
> Does it have to be the youtube video itself or can you do something like an audio only mode?

It has to be the youtube iframe itself, its term prohibits the separation of audio and video.

> Great to hear that these things are happening! I can't wait to be able to play this game without any issues. <3

The low graphics mode is now added! For now it only disables the hit and fever effects. Could you confirm whether the game runs smoother on your pc with the option turned on?

**Comment by Kweeme** [comment]
> It has to be the youtube iframe itself, its term prohibits the separation of audio and video.

Ah well it was worth a shot.

> The low graphics mode is now added!

This has greatly improved my FPS and the way the game runs entirely! Thanks for listening to my suggestions. Later I'm gonna try this on my phone, but I'm gonna safely say that this thread can now be closed. If you have any other remarks feel free to add them, or close this thread or I will next time I'm on.

**Comment by Kweeme** [comment]
> but I'm gonna safely say that this thread can now be closed. 

Of course I say this, then I find something else.. Idk if this is a bug or not, but turning on "Sync plays to youtube" makes songs infinitely load.

From console though idk if this is related to the bug or not.
`www-widgetapi.js:969 Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://www.youtube.com') does not match the recipient window's origin ('https://rhythm-plus.com').`

**Comment by henryzt** [comment]
> > but I'm gonna safely say that this thread can now be closed.
> 
> Of course I say this, then I find something else.. Idk if this is a bug or not, but turning on "Sync plays to youtube" makes songs infinitely load.

Yes, currently if you toggle this option in game, the youtube player would need a full reload to work. Also since it seems it doesn't really work (I don't think it syncs anything to youtube), I might just remove it.

**Comment by Kweeme** [comment]
> it doesn't really work (I don't think it syncs anything to youtube), I might just remove it.

Alrighty whatever you gotta do lmao.

## Another note...
I dunno if you've completely finished fixing the visualizer bug, but now whenever you head BACK to settings it sets it back to space visualizer.
