### ISSUE TITLE
Video stops playing from a removed ad.

### ISSUE THREAD

**Issue by UltraFatBoi** [henryzt/Rhythm-Plus-Music-Game#255]
On, Microsoft Edge, the video stops playing after an ad trys to play and it just says "Ad removed." and then the video doesn't play ever again, resulting in the song not working. Any fixes?
![Screenshot 2024-03-02 211830](https://github.com/henryzt/Rhythm-Plus-Music-Game/assets/138963208/d623e9a4-3271-460c-bb6d-bacdb863e3f2)

**Comment by henryzt** [comment]
Hi, thanks for the report! Could you send the link to the sheet where you experienced this? I have tried serveral but I can't find a Youtube embed that actually plays a mid-roll ad for me to test this.

**Comment by UltraFatBoi** [comment]
https://rhythm-plus.com/game/FDWCmB6TQMPNAm1VJcbohr
idk if this is it but here

**Comment by henryzt** [comment]
Sadly I still can't see any ads no matter the browser. Since I have no control of the ad and there are no events from Youtube or any method to load them for testing, I'm guessing the game cannot correctly handle them as of now.

Do you always see ads when you play this map, and does other maps show ads as well? If you change a browser, will it behave differently?

**Comment by UltraFatBoi** [comment]
Yes it happens on other maps and I was using Microsoft Edge
I'll just close this issue and play a different rhythm game like GPOP or somthing.

**Comment by UltraFatBoi** [comment]
I closed it
I'll just play GPOP for now.

**Comment by henryzt** [comment]
You can try to toggle 'Sync Plays to YouTube' option in the settings which could fix the issue. Additionally, we have planned to add a mode where the Youtube player is on the side similar to GPOP in v2. Could you please check if the same video displays ads when played in GPOP? 

I'd love to disscuss the issue further, if you prefer, feel free to find me on discord @format.z

Thanks again :)
